# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kacperks/Pulpit/Projects/Voxeler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kacperks/Pulpit/Projects/Voxeler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kacperks/Pulpit/Projects/Voxeler/CMakeFiles /home/kacperks/Pulpit/Projects/Voxeler//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kacperks/Pulpit/Projects/Voxeler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Voxeler

# Build rule for target.
Voxeler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Voxeler
.PHONY : Voxeler

# fast build rule for target.
Voxeler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/build
.PHONY : Voxeler/fast

src/app.o: src/app.cpp.o

.PHONY : src/app.o

# target to build an object file
src/app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/app.cpp.o
.PHONY : src/app.cpp.o

src/app.i: src/app.cpp.i

.PHONY : src/app.i

# target to preprocess a source file
src/app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/app.cpp.i
.PHONY : src/app.cpp.i

src/app.s: src/app.cpp.s

.PHONY : src/app.s

# target to generate assembly for a file
src/app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/app.cpp.s
.PHONY : src/app.cpp.s

src/engine/events/GLFWImp.o: src/engine/events/GLFWImp.cpp.o

.PHONY : src/engine/events/GLFWImp.o

# target to build an object file
src/engine/events/GLFWImp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/events/GLFWImp.cpp.o
.PHONY : src/engine/events/GLFWImp.cpp.o

src/engine/events/GLFWImp.i: src/engine/events/GLFWImp.cpp.i

.PHONY : src/engine/events/GLFWImp.i

# target to preprocess a source file
src/engine/events/GLFWImp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/events/GLFWImp.cpp.i
.PHONY : src/engine/events/GLFWImp.cpp.i

src/engine/events/GLFWImp.s: src/engine/events/GLFWImp.cpp.s

.PHONY : src/engine/events/GLFWImp.s

# target to generate assembly for a file
src/engine/events/GLFWImp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/events/GLFWImp.cpp.s
.PHONY : src/engine/events/GLFWImp.cpp.s

src/engine/fr.o: src/engine/fr.cpp.o

.PHONY : src/engine/fr.o

# target to build an object file
src/engine/fr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/fr.cpp.o
.PHONY : src/engine/fr.cpp.o

src/engine/fr.i: src/engine/fr.cpp.i

.PHONY : src/engine/fr.i

# target to preprocess a source file
src/engine/fr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/fr.cpp.i
.PHONY : src/engine/fr.cpp.i

src/engine/fr.s: src/engine/fr.cpp.s

.PHONY : src/engine/fr.s

# target to generate assembly for a file
src/engine/fr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/fr.cpp.s
.PHONY : src/engine/fr.cpp.s

src/engine/math/basic_functions.o: src/engine/math/basic_functions.cpp.o

.PHONY : src/engine/math/basic_functions.o

# target to build an object file
src/engine/math/basic_functions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/math/basic_functions.cpp.o
.PHONY : src/engine/math/basic_functions.cpp.o

src/engine/math/basic_functions.i: src/engine/math/basic_functions.cpp.i

.PHONY : src/engine/math/basic_functions.i

# target to preprocess a source file
src/engine/math/basic_functions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/math/basic_functions.cpp.i
.PHONY : src/engine/math/basic_functions.cpp.i

src/engine/math/basic_functions.s: src/engine/math/basic_functions.cpp.s

.PHONY : src/engine/math/basic_functions.s

# target to generate assembly for a file
src/engine/math/basic_functions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/math/basic_functions.cpp.s
.PHONY : src/engine/math/basic_functions.cpp.s

src/engine/math/quatenrion.o: src/engine/math/quatenrion.cpp.o

.PHONY : src/engine/math/quatenrion.o

# target to build an object file
src/engine/math/quatenrion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/math/quatenrion.cpp.o
.PHONY : src/engine/math/quatenrion.cpp.o

src/engine/math/quatenrion.i: src/engine/math/quatenrion.cpp.i

.PHONY : src/engine/math/quatenrion.i

# target to preprocess a source file
src/engine/math/quatenrion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/math/quatenrion.cpp.i
.PHONY : src/engine/math/quatenrion.cpp.i

src/engine/math/quatenrion.s: src/engine/math/quatenrion.cpp.s

.PHONY : src/engine/math/quatenrion.s

# target to generate assembly for a file
src/engine/math/quatenrion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/math/quatenrion.cpp.s
.PHONY : src/engine/math/quatenrion.cpp.s

src/engine/renderer/colorbuffer.o: src/engine/renderer/colorbuffer.cpp.o

.PHONY : src/engine/renderer/colorbuffer.o

# target to build an object file
src/engine/renderer/colorbuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/colorbuffer.cpp.o
.PHONY : src/engine/renderer/colorbuffer.cpp.o

src/engine/renderer/colorbuffer.i: src/engine/renderer/colorbuffer.cpp.i

.PHONY : src/engine/renderer/colorbuffer.i

# target to preprocess a source file
src/engine/renderer/colorbuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/colorbuffer.cpp.i
.PHONY : src/engine/renderer/colorbuffer.cpp.i

src/engine/renderer/colorbuffer.s: src/engine/renderer/colorbuffer.cpp.s

.PHONY : src/engine/renderer/colorbuffer.s

# target to generate assembly for a file
src/engine/renderer/colorbuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/colorbuffer.cpp.s
.PHONY : src/engine/renderer/colorbuffer.cpp.s

src/engine/renderer/depthbuffer.o: src/engine/renderer/depthbuffer.cpp.o

.PHONY : src/engine/renderer/depthbuffer.o

# target to build an object file
src/engine/renderer/depthbuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/depthbuffer.cpp.o
.PHONY : src/engine/renderer/depthbuffer.cpp.o

src/engine/renderer/depthbuffer.i: src/engine/renderer/depthbuffer.cpp.i

.PHONY : src/engine/renderer/depthbuffer.i

# target to preprocess a source file
src/engine/renderer/depthbuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/depthbuffer.cpp.i
.PHONY : src/engine/renderer/depthbuffer.cpp.i

src/engine/renderer/depthbuffer.s: src/engine/renderer/depthbuffer.cpp.s

.PHONY : src/engine/renderer/depthbuffer.s

# target to generate assembly for a file
src/engine/renderer/depthbuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/depthbuffer.cpp.s
.PHONY : src/engine/renderer/depthbuffer.cpp.s

src/engine/renderer/shader.o: src/engine/renderer/shader.cpp.o

.PHONY : src/engine/renderer/shader.o

# target to build an object file
src/engine/renderer/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/shader.cpp.o
.PHONY : src/engine/renderer/shader.cpp.o

src/engine/renderer/shader.i: src/engine/renderer/shader.cpp.i

.PHONY : src/engine/renderer/shader.i

# target to preprocess a source file
src/engine/renderer/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/shader.cpp.i
.PHONY : src/engine/renderer/shader.cpp.i

src/engine/renderer/shader.s: src/engine/renderer/shader.cpp.s

.PHONY : src/engine/renderer/shader.s

# target to generate assembly for a file
src/engine/renderer/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/shader.cpp.s
.PHONY : src/engine/renderer/shader.cpp.s

src/engine/renderer/vertexarray.o: src/engine/renderer/vertexarray.cpp.o

.PHONY : src/engine/renderer/vertexarray.o

# target to build an object file
src/engine/renderer/vertexarray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/vertexarray.cpp.o
.PHONY : src/engine/renderer/vertexarray.cpp.o

src/engine/renderer/vertexarray.i: src/engine/renderer/vertexarray.cpp.i

.PHONY : src/engine/renderer/vertexarray.i

# target to preprocess a source file
src/engine/renderer/vertexarray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/vertexarray.cpp.i
.PHONY : src/engine/renderer/vertexarray.cpp.i

src/engine/renderer/vertexarray.s: src/engine/renderer/vertexarray.cpp.s

.PHONY : src/engine/renderer/vertexarray.s

# target to generate assembly for a file
src/engine/renderer/vertexarray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/vertexarray.cpp.s
.PHONY : src/engine/renderer/vertexarray.cpp.s

src/engine/renderer/window.o: src/engine/renderer/window.cpp.o

.PHONY : src/engine/renderer/window.o

# target to build an object file
src/engine/renderer/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/window.cpp.o
.PHONY : src/engine/renderer/window.cpp.o

src/engine/renderer/window.i: src/engine/renderer/window.cpp.i

.PHONY : src/engine/renderer/window.i

# target to preprocess a source file
src/engine/renderer/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/window.cpp.i
.PHONY : src/engine/renderer/window.cpp.i

src/engine/renderer/window.s: src/engine/renderer/window.cpp.s

.PHONY : src/engine/renderer/window.s

# target to generate assembly for a file
src/engine/renderer/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Voxeler.dir/build.make CMakeFiles/Voxeler.dir/src/engine/renderer/window.cpp.s
.PHONY : src/engine/renderer/window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Voxeler"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/engine/events/GLFWImp.o"
	@echo "... src/engine/events/GLFWImp.i"
	@echo "... src/engine/events/GLFWImp.s"
	@echo "... src/engine/fr.o"
	@echo "... src/engine/fr.i"
	@echo "... src/engine/fr.s"
	@echo "... src/engine/math/basic_functions.o"
	@echo "... src/engine/math/basic_functions.i"
	@echo "... src/engine/math/basic_functions.s"
	@echo "... src/engine/math/quatenrion.o"
	@echo "... src/engine/math/quatenrion.i"
	@echo "... src/engine/math/quatenrion.s"
	@echo "... src/engine/renderer/colorbuffer.o"
	@echo "... src/engine/renderer/colorbuffer.i"
	@echo "... src/engine/renderer/colorbuffer.s"
	@echo "... src/engine/renderer/depthbuffer.o"
	@echo "... src/engine/renderer/depthbuffer.i"
	@echo "... src/engine/renderer/depthbuffer.s"
	@echo "... src/engine/renderer/shader.o"
	@echo "... src/engine/renderer/shader.i"
	@echo "... src/engine/renderer/shader.s"
	@echo "... src/engine/renderer/vertexarray.o"
	@echo "... src/engine/renderer/vertexarray.i"
	@echo "... src/engine/renderer/vertexarray.s"
	@echo "... src/engine/renderer/window.o"
	@echo "... src/engine/renderer/window.i"
	@echo "... src/engine/renderer/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

